import type { Metadata } from "next";
import "./globals.css";

import { Noto_Sans_JP } from "next/font/google";

const notoSansJP = Noto_Sans_JP();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.className} antialiased`}>{children}</body>
    </html>
  );
}
